inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/main/ci/rubocop.yml
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - 'pkg/**/*'

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 160
