source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-asciidoc", "~> 3.0"
gem "jekyll-remote-theme", "~> 0.4"
gem "jekyll-seo-tag", "~> 2.8"

group :jekyll_plugins do
  gem "just-the-docs", "~> 0.10"
end

gem "webrick", "~> 1.8"
